<?xml version="1.0"?>
<package format="2">
  <name>zed_camera_depth_cloud</name>
  <version>0.0.0</version>
  <description>ZED depth to pointcloud utilities</description>
  <maintainer email="root@localhost">root</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>sensor_msgs_py</depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>python3</exec_depend>
</package>
