<?xml version="1.0"?>
<package format="2">
  <name>zed_camera_depth_cloud</name>
  <version>0.0.0</version>
  <description>ZED depth to pointcloud utilities</description>
  <maintainer email="robot@localhost.local">robot</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>sensor_msgs_py</exec_depend>
  <exec_depend>python3</exec_depend>
</package>
