/**:
  ros__parameters:
    # usb_cam settings
    video_device: "/dev/video2"
    image_width: 1344
    image_height: 376
    framerate: 15.0
    pixel_format: "yuyv2rgb"
    camera_name: "zed_sbs"
    camera_info_url: ""

    # ZED Video mapped parameters (Mapped from 0-8 scale to v4l2 0-255 scale)
    brightness: 4
    contrast: 4
    saturation: 64
    sharpness: 128
    
    # Enable automatic adjustments by default
    auto_white_balance: true
    auto_exposure: 2
    
    # ZED Depth parameters
    min_depth: 0.5
    max_depth: 20.0
    point_cloud_freq: 15.0
    
    # ZED General parameters
    camera_model: "zed"
    grab_resolution: "WVGA"
    grab_frame_rate: 15