###################################################################################################
# GPS Visualization Tool
#
# This script takes in bag files generated by the rover to visualize the GPS data in 3D space. 
# It converts latitude, longitude, and altitude data into Cartesian coordinates.
#
# Uses matplotlib for 3D visualization.
#
# 1) Read data from specified csv file (or convert bag file to csv first)
# 2) Extract latitude, longitude, altitude and timestamp data
# 3) Convert lat, lon, alt to ENU coordinates using pyproj
# 4) Visualize the Cartesian coordinates in 3D space using matplotlib
# 
#
###################################################################################################

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from matplotlib.collections import LineCollection
from matplotlib.colors import Normalize
import matplotlib.cm as cm
import matplotlib.gridspec as gridspec

from pyproj import Transformer

# Fixing random state for reproducibility
np.random.seed(19680801)

fpab = pd.read_csv('data/gps_testAtoB.csv')
fpca = pd.read_csv('data/gps_testCtoA.csv')
fpbc = pd.read_csv('data/gps_testBtoC.csv')

# WGS84 lat/lon → ECEF
lla_to_ecef = Transformer.from_crs(
    "EPSG:4326",
    "EPSG:4978",
    always_xy=True
)

def convarr(fp):
    return fp[['timestamp', 'latitude', 'longitude','altitude']].to_numpy()

def get_ref_latlonalt(fp):
    # Get the reference latitude, longitude, and altitude from the first row of the DataFrame
    ref_lat = fp['latitude'][0]
    ref_lon = fp['longitude'][0]
    ref_alt = fp['altitude'][0]
    return ref_lat, ref_lon, ref_alt

def enu_rotation_matrix(lat, lon):
    lat = np.radians(lat)
    lon = np.radians(lon)

    return np.array([
        [-np.sin(lon),              np.cos(lon),               0],
        [-np.sin(lat)*np.cos(lon), -np.sin(lat)*np.sin(lon),  np.cos(lat)],
        [ np.cos(lat)*np.cos(lon),  np.cos(lat)*np.sin(lon),  np.sin(lat)]
    ])

def lla_to_ecef_xyz(latlonalt):
    x, y, z = lla_to_ecef.transform(latlonalt[1], latlonalt[0], latlonalt[2])
    return np.array([x, y, z])

def lla_to_enu(latlonalt, ref_ecef):
    ecef = lla_to_ecef_xyz(latlonalt)
    delta = ecef - ref_ecef
    return delta

def lat_lon_to_cartesian(lat, lon, altitude):
    # Convert latitude and longitude to Cartesian coordinates (x, y, z)

    R = 6371  # Earth radius in kilometers
    lat_rad = np.radians(lat)
    lon_rad = np.radians(lon)

    x = (R + altitude) * np.cos(lat_rad) * np.cos(lon_rad)
    y = (R + altitude) * np.cos(lat_rad) * np.sin(lon_rad)
    z = (R + altitude) * np.sin(lat_rad)

    return x, y, z

# FIX: Need to fix as lat lon will be inputed differently
def convert_to_cartesian(latitudes, longitudes, altitudes):
    cartesian_coords = []
    for lat, lon, alt in zip(latitudes, longitudes, altitudes):
        x, y, z = lat_lon_to_cartesian(lat, lon, alt)
        cartesian_coords.append((x, y, z))
    return cartesian_coords

# Actual GPS positions of waypoints A, B, C (lat, lon)
# Altitude set to sensor output
ACTUAL_WAYPOINTS = {
    'A': (43.6610182, -79.3948450, 73.0),
    'B': (43.661900,  -79.394179, 70),
    'C': (43.661505,  -79.396064, 70),
}

# Coords are in the form of a list of tuples: [(x1, y1, z1), (x2, y2, z2), ...]
def visualize_gps_data(rover_data, timestamps, actual_enu=None):
    E_vals, N_vals, U_vals = rover_data[:, 0], rover_data[:, 1], rover_data[:, 2]

    # Adjust timestamps 0.3<t<1 to ensure non-white color
    t = timestamps - timestamps.min()
    if t.max() > 0:
        t = t / t.max()
    t = 0.3 + t * 0.7

    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")

    # Plot line segments with gradient color
    for i in range(len(E_vals) - 1):
        ax.plot(
            E_vals[i:i+2], N_vals[i:i+2], U_vals[i:i+2],
            color=plt.cm.Blues(t[i]), linewidth=2
        )

    # Scatter plot for the dark to light blue gradient
    sc = ax.scatter(E_vals, N_vals, U_vals, c=t, cmap='Blues', vmin=0.3, vmax=1.0, s=10, linewidths=1)

    # Plot actual waypoint positions
    if actual_enu:
        for label, (e, n, u) in actual_enu.items():
            ax.scatter(e, n, u, marker='^', s=120, edgecolors='black', zorder=5, color='red')
            ax.text(e, n, u, f'  {label}', fontsize=10, fontweight='bold')
    
    ax.set_zlim(-20,20)

    cbar = fig.colorbar(sc, ax=ax, shrink=0.6, pad=0.1)
    cbar.set_ticks([0.3, 1.0])
    cbar.set_ticklabels(["Start", "End"])
    cbar.set_label("Time")

    ax.set_xlabel("East (m)")
    ax.set_ylabel("North (m)")
    ax.set_zlabel("Up (m)")
    ax.set_title("Rover Path (ENU Frame)")

    plt.show()


def processvis(fp, waypoint_labels=None):

    # Setup reference point for ENU conversion (using the first point in the dataset as reference)
    ref_lat, ref_lon, ref_alt = get_ref_latlonalt(fp)
    ref_ecef = lla_to_ecef_xyz(np.array([ref_lat, ref_lon, ref_alt]))

    R = enu_rotation_matrix(ref_lat, ref_lon)

    rover_data = np.empty((0, 3))
    timestamps = fp['timestamp'].to_numpy().astype(float)

    for i in range(len(fp)):
        latlonalt = fp[['latitude', 'longitude', 'altitude']].iloc[i].to_numpy()
        E, N, U = R @ lla_to_enu(latlonalt, ref_ecef)
        print(f"Data Point {i}: Lat={latlonalt[0]}, Lon={latlonalt[1]}, Alt={latlonalt[2]} -> E={E}, N={N}, U={U}")
        rover_data = np.append(rover_data, [[E, N, U]], axis=0)

    # Convert actual waypoints to ENU using the same reference
    actual_enu = None
    if waypoint_labels:
        actual_enu = {}
        for label in waypoint_labels:
            wlat, wlon,walt = ACTUAL_WAYPOINTS[label]
            wlatlonalt = np.array([wlat, wlon, walt])
            E, N, U = R @ lla_to_enu(wlatlonalt, ref_ecef)
            actual_enu[label] = (E, N, U)

    print(rover_data)
    visualize_gps_data(rover_data, timestamps, actual_enu=actual_enu)


def plot_entire_path():
    # Converting all data to ENU coordinates and plotting the entire path
    ref_lat, ref_lon, ref_alt = get_ref_latlonalt(fpab)
    ref_ecef = lla_to_ecef_xyz(np.array([ref_lat, ref_lon, ref_alt]))

    R = enu_rotation_matrix(ref_lat, ref_lon)

    rover_data = np.empty((0, 3))
    # timestamps = fp['timestamp'].to_numpy().astype(float)
    timestamps = np.concatenate([fpab['timestamp'].astype(float), fpbc['timestamp'].astype(float), fpca['timestamp'].astype(float)])

    for fp in [fpab, fpbc, fpca]:
        for i in range(len(fp)):
            latlonalt = fp[['latitude', 'longitude', 'altitude']].iloc[i].to_numpy()
            E, N, U = R @ lla_to_enu(latlonalt, ref_ecef)
            #print(f"Data Point {i}: Lat={latlonalt[0]}, Lon={latlonalt[1]}, Alt={latlonalt[2]} -> E={E}, N={N}, U={U}")
            rover_data = np.append(rover_data, [[E, N, U]], axis=0)

    visualize_gps_data_2d(rover_data, timestamps)

def colored_segments(ax, x, y, values, cmap, norm, lw=2.0):
        pts  = np.array([x, y]).T.reshape(-1, 1, 2)
        segs = np.concatenate([pts[:-1], pts[1:]], axis=1)
        lc   = LineCollection(segs, cmap=cmap, norm=norm, linewidth=lw,
                              capstyle="round")
        lc.set_array(values[:-1])
        ax.add_collection(lc)
        return lc

def visualize_gps_data_2d(rover_data, timestamps):
    E_vals, N_vals, U_vals = rover_data[:, 0], rover_data[:, 1], rover_data[:, 2]

    t = timestamps - timestamps.min()
    
    ds_horiz = np.sqrt(np.diff(E_vals)**2 + np.diff(N_vals)**2)
    ds_3d    = np.sqrt(ds_horiz**2 + np.diff(U_vals)**2)
    cum_dist    = np.concatenate([[0], np.cumsum(ds_3d)]) 

    fig = plt.figure(figsize=(14, 10), facecolor="#0d1117")
    fig.suptitle("Rover Path Analysis", color="#e6edf3", fontsize=15,
                 fontweight="bold", y=0.98)
    
    gs = gridspec.GridSpec(
        2, 1,
        figure=fig,
        left=0.07, right=0.93,
        top=0.93,  bottom=0.08,
        wspace=0.38, hspace=0.42,
    )

    ax_plan  = fig.add_subplot(gs[0, 0])   # left  – footprint
    ax_alt   = fig.add_subplot(gs[1, 0])   # right – altitude

    cmap  = cm.plasma
    norm  = Normalize(vmin=t[0], vmax=t[-1])

    lc_plan = colored_segments(ax_plan, E_vals, N_vals, t, cmap, norm)
    ax_plan.autoscale()
    ax_plan.set_aspect("equal")
    ax_plan.set_xlabel("East (m)")
    ax_plan.set_ylabel("North (m)")
    ax_plan.set_title("Top-Down Footprint")

    ax_plan.plot(E_vals[0],  N_vals[0],  marker="D", ms=8,
                 color="#3fb950", zorder=5, label="Start")
    ax_plan.plot(E_vals[-1], N_vals[-1], marker="s", ms=8,
                 color="#f85149", zorder=5, label="End")
    ax_plan.legend(fontsize=8, facecolor="#161b22", edgecolor="#30363d",
                   labelcolor="#e6edf3", loc="best")

    cb1 = fig.colorbar(lc_plan, ax=ax_plan, pad=0.02, fraction=0.035)
    cb1.set_label("Time", color="#8b949e", fontsize=8)
    cb1.ax.yaxis.set_tick_params(color="#8b949e", labelsize=7)
    plt.setp(cb1.ax.yaxis.get_ticklabels(), color="#8b949e")

    lc_alt = colored_segments(ax_alt, cum_dist, U_vals, t, cmap, norm)
    ax_alt.autoscale()
    ax_alt.set_xlabel("Cumulative Distance (m)")
    ax_alt.set_ylabel("Up / Altitude (m)")
    ax_alt.set_title("Altitude Profile")
    ax_alt.fill_between(cum_dist, U_vals.min() - 0.5, U_vals,
                        alpha=0.15, color="#58a6ff")

    cb2 = fig.colorbar(lc_alt, ax=ax_alt, pad=0.02, fraction=0.035)
    cb2.set_label("Time (s)", color="#8b949e", fontsize=8)
    cb2.ax.yaxis.set_tick_params(color="#8b949e", labelsize=7)
    plt.setp(cb2.ax.yaxis.get_ticklabels(), color="#8b949e")

    plt.show()

# ADD: Use arguments to specify the csv or bag file to visualize
if __name__ == "__main__":
    plot_entire_path()