###################################################################################################
# GPS Visualization Tool
#
# This script takes in bag files generated by the rover to visualize the GPS data in 3D space. 
# It converts latitude, longitude, and altitude data into Cartesian coordinates.
#
# Uses matplotlib for 3D visualization.
#
# 1) Read data from specified csv file (or convert bag file to csv first)
# 2) Extract latitude, longitude, altitude and timestamp data
# 3) Convert lat, lon, alt to UTM coordinates using pyproj
# 4) Visualize the Cartesian coordinates in 3D space using matplotlib
# 
#
###################################################################################################

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from pyproj import Transformer

# Fixing random state for reproducibility
np.random.seed(19680801)

fpab = pd.read_csv('data/gps_testAtoB.csv')
fpca = pd.read_csv('data/gps_testCtoA.csv')
fpbc = pd.read_csv('data/gps_testBtoC.csv')

# WGS84 lat/lon → ECEF
lla_to_ecef = Transformer.from_crs(
    "EPSG:4326",
    "EPSG:4978",
    always_xy=True
)

def convarr(fp):
    return fp[['timestamp', 'latitude', 'longitude','altitude']].to_numpy()

def get_ref_latlonalt(fp):
    # Get the reference latitude, longitude, and altitude from the first row of the DataFrame
    ref_lat = fp['latitude'][0]
    ref_lon = fp['longitude'][0]
    ref_alt = fp['altitude'][0]
    return ref_lat, ref_lon, ref_alt

def enu_rotation_matrix(lat, lon):
    lat = np.radians(lat)
    lon = np.radians(lon)

    return np.array([
        [-np.sin(lon),              np.cos(lon),               0],
        [-np.sin(lat)*np.cos(lon), -np.sin(lat)*np.sin(lon),  np.cos(lat)],
        [ np.cos(lat)*np.cos(lon),  np.cos(lat)*np.sin(lon),  np.sin(lat)]
    ])

def lla_to_ecef_xyz(latlonalt):
    x, y, z = lla_to_ecef.transform(latlonalt[1], latlonalt[0], latlonalt[2])
    return np.array([x, y, z])

def lla_to_enu(latlonalt):
    ecef = lla_to_ecef_xyz(latlonalt)
    delta = ecef - ref_ecef
    return delta 

def lat_lon_to_cartesian(lat, lon, altitude):
    # Convert latitude and longitude to Cartesian coordinates (x, y, z)

    R = 6371  # Earth radius in kilometers
    lat_rad = np.radians(lat)
    lon_rad = np.radians(lon)

    x = (R + altitude) * np.cos(lat_rad) * np.cos(lon_rad)
    y = (R + altitude) * np.cos(lat_rad) * np.sin(lon_rad)
    z = (R + altitude) * np.sin(lat_rad)

    return x, y, z

# FIX: Need to fix as lat lon will be inputed differently
def convert_to_cartesian(latitudes, longitudes, altitudes):
    cartesian_coords = []
    for lat, lon, alt in zip(latitudes, longitudes, altitudes):
        x, y, z = lat_lon_to_cartesian(lat, lon, alt)
        cartesian_coords.append((x, y, z))
    return cartesian_coords

# Coords are in the form of a list of tuples: [(x1, y1, z1), (x2, y2, z2), ...]
def visualize_gps_data(cartesian_coords):
    fig = plt.figure()
    ax = fig.add_subplot(projection='3d')

    # Adds points to the 3D scatter plot using the Cartesian coordinates
    for coord in cartesian_coords:
        # ADD: color based on timestamp later
        ax.scatter(coord[0], coord[1], coord[2], marker='o')

    ax.set_xlabel('X (km)')
    ax.set_ylabel('Y (km)')
    ax.set_zlabel('Z (km)')

    ax.set_title('3D Visualization of GPS Data')
    plt.show()

# ADD: Use arguments to specify the csv or bag file to visualize
if __name__ == "__main__":
    # Setup reference point for ENU conversion (using the first point in the dataset as reference)
    fp = fpca  # Example: using the A to B dataset for reference

    ref_lat, ref_lon, ref_alt = get_ref_latlonalt(fp)
    ref_ecef = lla_to_ecef_xyz(np.array([ref_lat, ref_lon, ref_alt]))
    R = enu_rotation_matrix(ref_lat, ref_lon)

    for i in range(len(fp)):
        latlonalt = fp[['latitude', 'longitude', 'altitude']].iloc[i].to_numpy()
        E, N, U = R @ lla_to_enu(latlonalt)
        print(f"Point {i}: E={E:.2f} m, N={N:.2f} m, U={U:.2f} m")