<?xml version="1.0"?>
<package format="3">
  <name>depth_detection</name>
  <version>0.0.1</version>
  <description>Point cloud filter for obstacle and ramp detection from ZED depth camera.</description>
  <maintainer email="robotswithai@example.com">robotswithai</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>rcl_interfaces</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>
  <depend>sensor_msgs</depend>
  <depend>sensor_msgs_py</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
